print("-- [Loading] Mounts Category")

local MainTabName = 'Mounts'

IGS.Category[MainTabName] = IGS.Category[MainTabName] or {
	[MainTabName] = {Packs = {}, Pointer = nil}
}

--	AddMallPack('Pack Title', 'Description', Price, 'Hot', Items ({ID, ID, ID} or {{ID =, Qty = , Qly = }, {ID =, Qty = , Qly = }), Ignored?, StockQty)
-- IGS.Category[MainTabName][MainTabName].Packs[1]	= AddMallPack("Cuddly Lamb Mount", "A companion to get along with your journey.", 399, 1, {9501}, 1, -1)
-- IGS.Category[MainTabName][MainTabName].Packs[2]	= AddMallPack("Witch Broomstick Mount", "A companion to get along with your journey.", 699, 1, {9502}, 1, -1)
-- IGS.Category[MainTabName][MainTabName].Packs[3]	= AddMallPack("Pink Ostrich Mount", "A companion to get along with your journey.", 699, 1, {9503}, 1, -1)
-- IGS.Category[MainTabName][MainTabName].Packs[4]	= AddMallPack("Squirrel Mount", "A companion to get along with your journey.", 799, 1, {9515}, 1, -1)
-- IGS.Category[MainTabName][MainTabName].Packs[5]	= AddMallPack("Tortoise Mount", "A companion to get along with your journey.", 699, 1, {9507}, 1, -1)
-- IGS.Category[MainTabName][MainTabName].Packs[6]	= AddMallPack("Elephant King Mount", "A companion to get along with your journey.", 699, 1, {9513}, 1, -1)
-- IGS.Category[MainTabName][MainTabName].Packs[7]	= AddMallPack("Baby Rockets Mount", "A companion to get along with your journey.", 699, 1, {9514}, 1, -1)
-- IGS.Category[MainTabName][MainTabName].Packs[8]	= AddMallPack("Little Wolf Mount", "A companion to get along with your journey.", 799, 1, {9511}, 1, -1)
-- IGS.Category[MainTabName][MainTabName].Packs[9]	= AddMallPack("Pink Deer Mount", "A companion to get along with your journey.", 699, 1, {9510}, 1, -1)
-- IGS.Category[MainTabName][MainTabName].Packs[10] = AddMallPack("Rat King Mount", "A companion to get along with your journey.", 699, 1, {9509}, 1, -1)
-- IGS.Category[MainTabName][MainTabName].Packs[11] = AddMallPack("T-Rex Mount", "A companion to get along with your journey.", 899, 1, {9508}, 1, -1)
-- IGS.Category[MainTabName][MainTabName].Packs[12] = AddMallPack("Little Cat Mount", "A companion to get along with your journey.", 799, 1, {9505}, 1, -1)
-- IGS.Category[MainTabName][MainTabName].Packs[13] = AddMallPack("Lycan Mount", "A companion to get along with your journey.", 899, 1, {9504}, 1, -1)
-- IGS.Category[MainTabName][MainTabName].Packs[14] = AddMallPack("Baby Black Dragon Mount", "A companion to get along with your journey.", 899, 1, {9500}, 1, -1)
--New Mounts
IGS.Category[MainTabName][MainTabName].Packs[1]	= AddMallPack("Black Bird Mount", "A companion to get along with your journey.", 1200, 1, {10101}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[2]	= AddMallPack("Dragon Warrior Mount", "A companion to get along with your journey.", 1200, 1, {10102}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[3]	= AddMallPack("Unicorn Mount", "A companion to get along with your journey.", 899, 1, {10103}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[4]	= AddMallPack("Evil Dragon Bat Mount", "A companion to get along with your journey.", 899, 1, {10104}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[5]	= AddMallPack("Warrior Fire Horse", "A companion to get along with your journey.", 1399, 1, {10105}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[6]	= AddMallPack("Night Horse Mount", "A companion to get along with your journey.", 1100, 1, {10106}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[7]	= AddMallPack("Black Dragon Beast", "A companion to get along with your journey.", 1100, 1, {10107}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[8]	= AddMallPack("United Eagle Mount", "A companion to get along with your journey.", 1100, 1, {10108}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[9]	= AddMallPack("Pinky Mount", "A companion to get along with your journey.", 1100, 1, {10109}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[10] = AddMallPack("Eagle Beast Mount", "A companion to get along with your journey.", 1100, 1, {10110}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[11] = AddMallPack("Panda Dog", "A companion to get along with your journey.", 1100, 1, {10111}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[12] = AddMallPack("Warrior Horse Mount", "A companion to get along with your journey.", 1299, 1, {10113}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[13] = AddMallPack("Leopard Beast", "A companion to get along with your journey.", 1199, 1, {10114}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[14] = AddMallPack("Venom Spider", "A companion to get along with your journey.", 1100, 1, {10115}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[15] = AddMallPack("Lizard Warrior", "A companion to get along with your journey.", 1100, 1, {10116}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[16] = AddMallPack("Blue Eagle Mount", "A companion to get along with your journey.", 1599, 1, {10117}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[17] = AddMallPack("Warrior Tiger Mount", "A companion to get along with your journey.", 1699, 1, {10118}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[18] = AddMallPack("Double Headed Mount", "A companion to get along with your journey.", 1499, 1, {10119}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[19] = AddMallPack("Statue Guardian Mount", "A companion to get along with your journey.", 1100, 1, {10120}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[20] = AddMallPack("Angelic Wolve Mount", "A companion to get along with your journey.", 1899, 1, {10121}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[21] = AddMallPack("Pink Eagle Mount", "A companion to get along with your journey.", 1299, 1, {10122}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[22] = AddMallPack("White Eagle", "A companion to get along with your journey.", 1199, 1, {10123}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[23] = AddMallPack("Evil Bat Mount", "A companion to get along with your journey.", 1100, 1, {10124}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[24] = AddMallPack("Beast Dragon Mount", "A companion to get along with your journey.", 1799, 1, {10125}, 1, -1)
IGS.Category[MainTabName][MainTabName].Packs[25] = AddMallPack("Winter Eagle", "A companion to get along with your journey.", 1799, 1, {10126}, 1, -1)
IGS.Category[MainTabName][MainTabName].Pointer = AddMallTab(MainTabName, IGS.Category[MainTabName][MainTabName].Packs)
