print("-- [Loading] Learn All Skills]")

function fullskills1 (role)
---Swordsman
AddChaSkill ( role , SK_CHF , 10 , 0 , 0 )
AddChaSkill ( role , SK_JDZZ , 10 , 0 , 0 )
AddChaSkill ( role , SK_GTYZ , 10 , 0 , 0 )
AddChaSkill ( role , SK_JSSL , 10 , 0 , 0 )
AddChaSkill ( role , SK_HYZ , 10 , 0 , 0 )
AddChaSkill ( role , SK_PJ , 10 , 0 , 0 )
AddChaSkill ( role , SK_KB , 10 , 0 , 0 )
AddChaSkill ( role , SK_HX , 10 , 0 , 0 )
---Crusader
AddChaSkill ( role , SK_FSZ , 10 , 0 , 0 )
AddChaSkill ( role , SK_PXKG , 10 , 0 , 0 )
AddChaSkill ( role , SK_LQHB , 10 , 0 , 0 )
AddChaSkill ( role , SK_YS , 10 , 0 , 0 )
AddChaSkill ( role , SK_GWZ , 10 , 0 , 0 )
AddChaSkill ( role , SK_DB , 10 , 0 , 0 )
---Champion
AddChaSkill ( role , SK_JJSL , 10 , 0 , 0 )
AddChaSkill ( role , SK_MNRX , 10 , 0 , 0 )
AddChaSkill ( role , SK_SWZQ , 10 , 0 , 0 )
AddChaSkill ( role , SK_QHTZ , 10 , 0 , 0 )
AddChaSkill ( role , SK_ZJ , 10 , 0 , 0 )
AddChaSkill ( role , SK_LH , 10 , 0 , 0 )
---Explorer
AddChaSkill ( role , SK_JR , 10 , 0 , 0 )
AddChaSkill ( role , SK_LJ , 10 , 0 , 0 )
AddChaSkill ( role , SK_SL , 10 , 0 , 0 )
AddChaSkill ( role , SK_BKZJ , 10 , 0 , 0 )
AddChaSkill ( role , SK_JF , 10 , 0 , 0 )
AddChaSkill ( role , SK_HZCR , 10 , 0 , 0 )
---Voyager
AddChaSkill ( role , SK_BKCJ , 10 , 0 , 0 )
AddChaSkill ( role , SK_SF , 10 , 0 , 0 )
AddChaSkill ( role , SK_XW , 10 , 0 , 0 )
AddChaSkill ( role , SK_MW , 10 , 0 , 0 )
AddChaSkill ( role , SK_LM , 10 , 0 , 0 )
---Hunter
AddChaSkill ( role , SK_GJSL , 10 , 0 , 0 )
AddChaSkill ( role , SK_JFB , 10 , 0 , 0 )
AddChaSkill ( role , SK_LZJ , 10 , 0 , 0 )
AddChaSkill ( role , SK_FNQ , 10 , 0 , 0 )
AddChaSkill ( role , SK_DJ , 10 , 0 , 0 )
AddChaSkill ( role , SK_BDJ , 10 , 0 , 0 )
AddChaSkill ( role , SK_LXJY , 10 , 0 , 0 )
---Sharpshooter
AddChaSkill ( role , SK_HQSL , 10 , 0 , 0 )
AddChaSkill ( role , SK_RSD , 10 , 0 , 0 )
AddChaSkill ( role , SK_TJ , 10 , 0 , 0 )
AddChaSkill ( role , SK_SJ , 10 , 0 , 0 )
AddChaSkill ( role , SK_BT , 10 , 0 , 0 )
---Herbalist
AddChaSkill ( role , SK_XZY , 10 , 0 , 0 )
AddChaSkill ( role , SK_JSJC , 10 , 0 , 0 )
AddChaSkill ( role , SK_XLCZ , 10 , 0 , 0 )
AddChaSkill ( role , SK_HFS , 10 , 0 , 0 )
AddChaSkill ( role , SK_FH , 10 , 0 , 0 )
---Cleric
AddChaSkill ( role , SK_SY , 10 , 0 , 0 )
AddChaSkill ( role , SK_SYZY , 10 , 0 , 0 )
AddChaSkill ( role , SK_BUFFCL , 10 , 0 , 0 )
AddChaSkill ( role , SK_HFWQ , 10 , 0 , 0 )
AddChaSkill ( role , SK_XLPZ , 10 , 0 , 0 )
AddChaSkill ( role , SK_BLYZ , 10 , 0 , 0 )
---SealMaster
AddChaSkill ( role , SK_SY , 10 , 0 , 0 )
AddChaSkill ( role , SK_BUFFSM , 10 , 0 , 0 )
AddChaSkill ( role , SK_SYZY , 10 , 0 , 0 )
AddChaSkill ( role , SK_ZZZH , 10 , 0 , 0 )
AddChaSkill ( role , SK_SYNZ , 10 , 0 , 0 )
AddChaSkill ( role , SK_AYZZ , 10 , 0 , 0 )
AddChaSkill ( role , SK_XZFY , 10 , 0 , 0 )
AddChaSkill ( role , SK_MLCH , 10 , 0 , 0 )
end
